/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agent.chat;

import javax.swing.JOptionPane;
import java.io.File;

/**
 *
 * @author titip
 */
public class RegisterGui extends javax.swing.JFrame {

    /**
     * Creates new form RegisterGui
     */
    
    String profileimagepath;
    
    public RegisterGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        mainTxt_jLabel = new javax.swing.JLabel();
        email_jTextField = new javax.swing.JTextField();
        username_JtextField = new javax.swing.JTextField();
        image_select_jbutton = new javax.swing.JButton();
        register_jbutton = new javax.swing.JButton();
        password_jField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTxt_jLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        mainTxt_jLabel.setForeground(new java.awt.Color(255, 0, 0));
        mainTxt_jLabel.setText("AgentChat - Register");

        email_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_jTextFieldActionPerformed(evt);
            }
        });

        username_JtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_JtextFieldActionPerformed(evt);
            }
        });

        image_select_jbutton.setText("Pick Image Profile");
        image_select_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_select_jbuttonActionPerformed(evt);
            }
        });

        register_jbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        register_jbutton.setText("Register");
        register_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_jbuttonActionPerformed(evt);
            }
        });

        password_jField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_jFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image_select_jbutton)
                        .addGap(53, 53, 53)
                        .addComponent(register_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainTxt_jLabel)
                                        .addGap(103, 103, 103))
                                    .addComponent(username_JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_jField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(email_jTextField))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainTxt_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_jField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(image_select_jbutton)
                    .addComponent(register_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_JtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_JtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_JtextFieldActionPerformed

    private void image_select_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_select_jbuttonActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(null);
        if (returnValue == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            this.profileimagepath = selectedFile.getAbsolutePath();
            System.out.println("profile image selected : " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_image_select_jbuttonActionPerformed

    private void register_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_jbuttonActionPerformed
       FileOperation filework = new FileOperation();
       String username = username_JtextField.getText();
       if (username.equals("")) {
           JOptionPane.showMessageDialog(null,"Username not specified","Register Error",2);
       }
       String password = password_jField.getText();
       if (password.equals("")) {
           JOptionPane.showMessageDialog(null,"Password not specified","Register Error",2);
       }
       String email = email_jTextField.getText();
       if (email.equals("")) {
           JOptionPane.showMessageDialog(null,"Email not specified","Register Error",2);
       }
       if (!email.contains("@")) {
           JOptionPane.showMessageDialog(null,"Invalid Email ! ","Register Error",2);
       }
       if (!email.equals("") && !password.equals("") && !username.equals("")) {
           try {
                filework.createNewProfile(username, password, email, this.profileimagepath); 
                JOptionPane.showMessageDialog(null,"Profile Created","Information",1);
                LoginGui lgui = new LoginGui();
                String[] args = null;
                lgui.main(args);
           }
            catch (Exception e) {
                e.printStackTrace();
            }
       }
       

    }//GEN-LAST:event_register_jbuttonActionPerformed

    private void email_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_jTextFieldActionPerformed

    private void password_jFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_jFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_jFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_jTextField;
    private javax.swing.JButton image_select_jbutton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mainTxt_jLabel;
    private javax.swing.JPasswordField password_jField;
    private javax.swing.JButton register_jbutton;
    private javax.swing.JTextField username_JtextField;
    // End of variables declaration//GEN-END:variables
}
